"""initial schema

Revision ID: 91dbd1086032
Revises: 
Create Date: 2026-09-23 15:30:50.477342
"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


revision = '91dbd1086032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('issue_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.CheckConstraint('horizon_hours IN (24, 48)', name='ck_run_horizon_hours'),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_run_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_status'), 'forecast_runs', ['status'], unique=False)
    op.create_table('turbines',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table('turbines', sa.column('id', sa.String), sa.column('name', sa.String),
                 sa.column('latitude', sa.Float), sa.column('longitude', sa.Float),
                 sa.column('created_at', sa.DateTime)),
        [
            {'id': '1', 'name': 'Turbine 1', 'latitude': 43.645150, 'longitude': 78.535604, 'created_at': datetime.utcnow()},
            {'id': '2', 'name': 'Turbine 2', 'latitude': 43.643198, 'longitude': 78.538828, 'created_at': datetime.utcnow()},
        ],
    )
    op.create_table('forecast_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('turbine_id', sa.String(length=40), nullable=False),
    sa.Column('target_time', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('wind_speed_100m_ms', sa.Float(), nullable=True),
    sa.Column('temperature_2m_c', sa.Float(), nullable=True),
    sa.CheckConstraint('power >= 0 AND power <= 1', name='ck_forecast_power_normalized'),
    sa.CheckConstraint('horizon_hours >= 1 AND horizon_hours <= 48', name='ck_forecast_value_horizon'),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'turbine_id', 'target_time', name='uq_forecast_run_target')
    )
    op.create_index('ix_forecast_values_run_target', 'forecast_values', ['run_id', 'target_time'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbine_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wind_ms', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.CheckConstraint('power >= 0 AND power <= 1', name='ck_measurement_power_normalized'),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turbine_id', 'timestamp', name='uq_measurement_turbine_timestamp')
    )
    op.create_index('ix_measurements_turbine_timestamp', 'measurements', ['turbine_id', 'timestamp'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbine_id', sa.String(length=40), nullable=False),
    sa.Column('target_time', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('lead_hours', sa.Integer(), nullable=False),
    sa.Column('wind_speed_100m_ms', sa.Float(), nullable=True),
    sa.Column('wind_direction_100m_deg', sa.Float(), nullable=True),
    sa.Column('temperature_2m_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m_pct', sa.Float(), nullable=True),
    sa.Column('wind_gusts_10m_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.CheckConstraint('lead_hours IN (24, 48)', name='ck_weather_lead_hours'),
    sa.ForeignKeyConstraint(['turbine_id'], ['turbines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turbine_id', 'target_time', 'lead_hours', 'issued_at', name='uq_weather_vintage')
    )
    op.create_index('ix_weather_target_lead', 'weather_forecasts', ['target_time', 'lead_hours'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_target_lead', table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_measurements_turbine_timestamp', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_forecast_values_run_target', table_name='forecast_values')
    op.drop_table('forecast_values')
    op.drop_table('turbines')
    op.drop_index(op.f('ix_forecast_runs_status'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
